-- Pre-seed stores with deterministic IDs.
-- Uses OVERRIDING SYSTEM VALUE because store_id is GENERATED BY DEFAULT AS IDENTITY.

INSERT INTO stores (store_id, name) OVERRIDING SYSTEM VALUE VALUES
    (1, 'coop'),
    (2, 'hemkop'),
    (3, 'ica'),
    (4, 'mathem'),
    (5, 'willys')
ON CONFLICT (name) DO NOTHING;

-- Advance the identity sequence past the seeded IDs so future inserts don't collide.
SELECT setval(pg_get_serial_sequence('stores', 'store_id'), 5, true);
