-- Normalized schema for supermarket inventory data

CREATE TABLE IF NOT EXISTS stores (
    store_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS categories (
    category_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                TEXT NOT NULL,
    parent_category_id  BIGINT
        REFERENCES categories (category_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT uq_categories_name_parent UNIQUE NULLS NOT DISTINCT (name, parent_category_id)
);

CREATE TABLE IF NOT EXISTS products (
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    category_id BIGINT
        REFERENCES categories (category_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    description TEXT,
    sku         TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_products_name_category UNIQUE NULLS NOT DISTINCT (name, category_id)
);

CREATE TABLE IF NOT EXISTS quantity_types (
    quantity_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS units (
    unit_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    abbreviation TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS availability_statuses (
    availability_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   TEXT NOT NULL UNIQUE,
    description            TEXT
);

CREATE TABLE IF NOT EXISTS currencies (
    currency_code CHAR(3) PRIMARY KEY,
    name          TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS store_products (
    store_product_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id                BIGINT NOT NULL
        REFERENCES stores (store_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    product_id              BIGINT NOT NULL
        REFERENCES products (product_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    external_store_sku      TEXT,
    url                     TEXT,
    currency_code           CHAR(3)
        REFERENCES currencies (currency_code)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    price                   NUMERIC(12, 2),
    unit_price              NUMERIC(12, 4),
    unit_quantity           NUMERIC(12, 4),
    unit_id                 BIGINT
        REFERENCES units (unit_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    quantity_type_id        BIGINT
        REFERENCES quantity_types (quantity_type_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    availability_status_id  BIGINT
        REFERENCES availability_statuses (availability_status_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    nutrition_raw           JSONB,
    notes                   TEXT,
    first_seen_at           TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at            TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT chk_price_non_negative
        CHECK (price IS NULL OR price >= 0),
    CONSTRAINT chk_unit_price_non_negative
        CHECK (unit_price IS NULL OR unit_price >= 0),
    CONSTRAINT chk_unit_quantity_positive
        CHECK (unit_quantity IS NULL OR unit_quantity > 0),
    CONSTRAINT uq_store_products UNIQUE (store_id, product_id)
);

CREATE TABLE IF NOT EXISTS product_availability_history (
    history_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_product_id       BIGINT NOT NULL
        REFERENCES store_products (store_product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    availability_status_id BIGINT
        REFERENCES availability_statuses (availability_status_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    price                  NUMERIC(12, 2),
    unit_price             NUMERIC(12, 4),
    recorded_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger: record old price/availability before updates
CREATE OR REPLACE FUNCTION record_store_product_history()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO product_availability_history (
        store_product_id,
        availability_status_id,
        price,
        unit_price
    ) VALUES (
        OLD.store_product_id,
        OLD.availability_status_id,
        OLD.price,
        OLD.unit_price
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_store_product_history
    AFTER UPDATE ON store_products
    FOR EACH ROW
    WHEN (
        OLD.price IS DISTINCT FROM NEW.price
        OR OLD.unit_price IS DISTINCT FROM NEW.unit_price
        OR OLD.availability_status_id IS DISTINCT FROM NEW.availability_status_id
    )
    EXECUTE FUNCTION record_store_product_history();

-- Indexes to optimize lookups
CREATE INDEX IF NOT EXISTS idx_categories_parent
    ON categories (parent_category_id);

CREATE INDEX IF NOT EXISTS idx_products_category
    ON products (category_id);

CREATE INDEX IF NOT EXISTS idx_store_products_store
    ON store_products (store_id);

CREATE INDEX IF NOT EXISTS idx_store_products_product
    ON store_products (product_id);

CREATE INDEX IF NOT EXISTS idx_store_products_currency
    ON store_products (currency_code);

CREATE INDEX IF NOT EXISTS idx_product_availability_history_store_product
    ON product_availability_history (store_product_id);

CREATE INDEX IF NOT EXISTS idx_product_availability_history_recorded_at
    ON product_availability_history (recorded_at);